---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - stx-devstack-fault:
            voting: false
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - openstack-tox-linters
        - openstack-tox-pep8
    gate:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - openstack-tox-linters
        - openstack-tox-pep8
    post:
      jobs:
        - publish-stx-api-ref
        - publish-stx-tox
        - publish-stx-releasenotes

# This job is to begin testing a DevStack run here
- job:
    name: stx-devstack-base
    parent: devstack
    description: |
      Base job for StarlingX DevStack tests
    roles:
      - zuul: openstack-infra/devstack
    timeout: 9000
    required-projects:
      - name: git.openstack.org/openstack-dev/devstack
        override-branch: stable/pike
      - name: git.openstack.org/openstack/cinder
        override-branch: stable/pike
      - name: git.openstack.org/openstack/glance
        override-branch: stable/pike
      - name: git.openstack.org/openstack/keystone
        override-branch: stable/pike
      - name: git.openstack.org/openstack/neutron
        override-branch: stable/pike
      - name: git.openstack.org/openstack/nova
        override-branch: stable/pike
    vars:
      devstack_services:
        ceilometer-acentral: false
        ceilometer-acompute: false
        ceilometer-alarm-evaluator: false
        ceilometer-alarm-notifier: false
        ceilometer-anotification: false
        ceilometer-api: false
        ceilometer-collector: false
        horizon: false
        # Swift services
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        tempest: false
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^releasenotes/.*$

- job:
    name: stx-devstack-fault
    parent: stx-devstack-base
    timeout: 7800
    required-projects:
      - name: git.starlingx.io/stx-update
    vars:
      tox_envlist: functional
      devstack_plugins:
        stx-update: git://git.starlingx.io/stx-update
        stx-fault: git://git.starlingx.io/stx-fault
