---

- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - flock-devstack-fault
        - openstack-tox-linters
        - openstack-tox-pep8
        - stx-fault-build
    gate:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - flock-devstack-fault
        - openstack-tox-linters
        - openstack-tox-pep8
    post:
      jobs:
        - publish-stx-api-ref
        - publish-stx-tox
        - publish-stx-releasenotes

# Perform just a build
- job:
    name: stx-fault-build
    parent: tox
    description: Run build for fault
    irrelevant-files:
      - api-ref/*
      - docs/*
      - releasenotes/*
    vars:
      tox_envlist: build

# TODO(dtroyer): This job definition needs to stay here until none of
#                the other plugins are using it...
# This job is to begin testing a DevStack run here
- job:
    name: stx-devstack-base
    nodeset: openstack-single-node-bionic
    parent: devstack
    description: |
      Base job for StarlingX DevStack tests
    roles:
      - zuul: openstack-infra/devstack
    timeout: 9000
    required-projects:
      - name: git.openstack.org/openstack-dev/devstack
#      - name: git.openstack.org/openstack/cinder
#      - name: git.openstack.org/openstack/glance
      - name: git.openstack.org/openstack/keystone
#      - name: git.openstack.org/openstack/neutron
#      - name: git.openstack.org/openstack/nova
      - name: git.openstack.org/openstack/requirements
    vars:
      devstack_services:
        ceilometer-acentral: false
        ceilometer-acompute: false
        ceilometer-alarm-evaluator: false
        ceilometer-alarm-notifier: false
        ceilometer-anotification: false
        ceilometer-api: false
        ceilometer-collector: false
        horizon: false
        # Swift services
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        tempest: false
        # Database
        mysql: false
        postgresql: true
      devstack_localrc:
        # LIBS_FROM_GIT: cinder,glance,keystone,neutron,nova
        LIBS_FROM_GIT: keystone
        FORCE: yes

- job:
    name: flock-devstack-fault
    parent: flock-devstack-base-min
    required-projects:
      - name: openstack/stx-config
      - name: openstack/stx-integ
      - name: openstack/stx-update
    vars:
      tox_envlist: functional
      devstack_services:
        cgtsclient: true
        fm-common: true
        fm-api: true
        fm-rest-api: true
        fm-mgr: true
      devstack_plugins:
        stx-config: https://git.starlingx.io/stx-config
        stx-fault: https://git.starlingx.io/stx-fault
        stx-integ: https://git.starlingx.io/stx-integ
        stx-update: https://git.starlingx.io/stx-update

- job:
    name: fm-rest-api-functional
    parent: flock-devstack-fault
    description: |
      Functional/API tests for fm-rest-api
    vars:
      tox_envlist: functional
      tox_extra_args: -c fm-rest-api/fm/tox.ini
      tox_environment:
        # TODO(dtroyer): The test should learn to query the service catalog to get this
        OS_TEST_URL: "http://{{ ansible_default_ipv4.address }}:18002/"
    files:
      - fm-rest-api/*
