---
- project:
    check:
      jobs:
        - openstack-tox-pep8:
            voting: false
        - openstack-tox-linters:
            voting: false
    gate:
      jobs:
        - openstack-tox-pep8
