#!/bin/bash
# Devstack settings

# Services
# stx-fault - Overall enable for this plugin
# fm-client
# fm-common
# fm-api
# fm-rest-api
# fm-mgr

# Defaults
# --------

STX_FAULT_NAME=stx-fault

######### Plugin Specific ##########
enable_service $STX_FAULT_NAME

if is_service_enabled fm-rest-api; then
    enable_service tsconfig
fi

# Initial source of lib script
source $DEST/stx-fault/devstack/lib/stx-fault
