#!/bin/bash
# Devstack settings

# Defaults
# --------

STX_FAULT_NAME=stx-fault

######### Plugin Specific ##########
enable_service $STX_FAULT_NAME
#define_plugin $STX_FAULT_NAME

# Handle STX pre-reqs
if is_service_enabled fm-rest-api; then
	enable_service tsconfig
fi
